### ISSUE TITLE
Trying to follow the basic Rhythm Game example. The built app crashes on my phone before I even start adding to it.

### ISSUE THREAD

**Issue by interstar** [google/oboe#472]
I just get an "Unfortunately RhythmGame has stopped" with the default, out of the box tamplate. 

Before I start adding anything to it.

I'm testing on an Asus A007, Android 6.0.1, API 23

**Comment by dturner** [comment]
That is worrying. Please could you paste the full stack trace from logcat?

**Comment by interstar** [comment]
I don't know if it's relevant but there seem to be a bunch of permission denied messages.

```
data@app@com.google.oboe.sample.rhythmgame-2@split_lib_dependencies_apk.apk@classes.dex: Permission denied
04-25 15:35:02.382 30457-30457/? I/dex2oat: dex2oat took 873.646us (threads: 4) 
04-25 15:35:02.385 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.527 2045-2418/? D/VirtualKeyBackLightService: full screen state = false
04-25 15:35:02.636 30460-30460/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_0_apk.apk@classes.dex: Permission denied
04-25 15:35:02.636 30460-30460/? I/dex2oat: dex2oat took 755us (threads: 4) 
04-25 15:35:02.638 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.676 2045-2418/? D/VirtualKeyBackLightService: full screen state = false
04-25 15:35:02.678 2045-2418/? D/VirtualKeyBackLightService: full screen state = false
04-25 15:35:02.700 30466-30466/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_2_apk.apk@classes.dex: Permission denied
04-25 15:35:02.700 30466-30466/? I/dex2oat: dex2oat took 752.448us (threads: 4) 
04-25 15:35:02.702 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.757 30468-30468/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_3_apk.apk@classes.dex: Permission denied
04-25 15:35:02.757 30468-30468/? I/dex2oat: dex2oat took 736.354us (threads: 4) 
04-25 15:35:02.759 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.824 30470-30470/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_4_apk.apk@classes.dex: Permission denied
04-25 15:35:02.824 30470-30470/? I/dex2oat: dex2oat took 743.542us (threads: 4) 
04-25 15:35:02.826 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.879 30472-30472/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_5_apk.apk@classes.dex: Permission denied
04-25 15:35:02.879 30472-30472/? I/dex2oat: dex2oat took 740.312us (threads: 4) 
04-25 15:35:02.882 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:02.934 30474-30474/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_6_apk.apk@classes.dex: Permission denied
04-25 15:35:02.934 30474-30474/? I/dex2oat: dex2oat took 737.552us (threads: 4) 
04-25 15:35:02.936 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:03.003 30476-30476/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_7_apk.apk@classes.dex: Permission denied
04-25 15:35:03.003 30476-30476/? I/dex2oat: dex2oat took 750.521us (threads: 4) 
04-25 15:35:03.005 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:03.026 3618-4361/? D/NetworkController.MobileSignalController(1): onSignalStrengthsChanged signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 35 -106 -15 -40 2147483647 2147483647 gsm|lte level=3
04-25 15:35:03.026 3618-4361/? D/NetworkController.MobileSignalController(1): updateTelephonySignalStrength: hasService=true ss=SignalStrength: 99 0 -120 -160 -120 -1 -1 35 -106 -15 -40 2147483647 2147483647 gsm|lte
04-25 15:35:03.026 3618-4361/? D/NetworkController.MobileSignalController(1): ril.lteca.mode: 0
04-25 15:35:03.028 4187-27688/? D/PhoneInterfaceManager: isWifiCallingAvailable: sub Id : 1
04-25 15:35:03.028 3618-4361/? V/ReflectionMethods: ========ReflectionMethods.getWifiCallingAvailable = false ===============
04-25 15:35:03.030 4187-31674/? D/PhoneInterfaceManager: isVolteAvailable: sub Id : 1
04-25 15:35:03.030 3618-4361/? V/ReflectionMethods: ========ReflectionMethods.getVolteAvailable = false ===============
04-25 15:35:03.031 4187-4239/? D/PhoneInterfaceManager: isVideoTelephonyAvailable: sub Id : 1
04-25 15:35:03.031 3618-4361/? V/ReflectionMethods: ========ReflectionMethods.getVideoTelephonyAvailable = false ===============
04-25 15:35:03.062 30478-30478/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_8_apk.apk@classes.dex: Permission denied
04-25 15:35:03.062 30478-30478/? I/dex2oat: dex2oat took 737.396us (threads: 4) 
04-25 15:35:03.064 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:03.118 30481-30481/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_9_apk.apk@classes.dex: Permission denied
04-25 15:35:03.118 30481-30481/? I/dex2oat: dex2oat took 781.979us (threads: 4) 
04-25 15:35:03.120 30444-30444/com.google.oboe.sample.rhythmgame W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=div --dex-file=/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.google.oboe.sample.rhythmgame-2@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
04-25 15:35:03.128 30444-30444/com.google.oboe.sample.rhythmgame W/System: ClassLoader referenced unknown path: /data/app/com.google.oboe.sample.rhythmgame-2/lib/arm
04-25 15:35:03.131 30444-30444/com.google.oboe.sample.rhythmgame I/InstantRun: starting instant run server: is main process
04-25 15:35:03.135 30444-30444/com.google.oboe.sample.rhythmgame V/Monotype: SetAppTypeFace- try to flip, app = com.google.oboe.sample.rhythmgame
04-25 15:35:03.136 30444-30444/com.google.oboe.sample.rhythmgame V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
04-25 15:35:03.167 30444-30444/com.google.oboe.sample.rhythmgame D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
04-25 15:35:03.168 30444-30444/com.google.oboe.sample.rhythmgame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.oboe.sample.rhythmgame, PID: 30444
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.oboe.sample.rhythmgame-2/base.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.oboe.sample.rhythmgame-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.oboe.sample.rhythmgame.MainActivity.<clinit>(MainActivity.java:28)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2336)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5472)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 15:35:03.169 2045-7195/? D/ActivityManager: Prepare to send crash information Messege to SystemGaService
04-25 15:35:03.170 2045-7195/? D/PackageSettings: getInstallerPackageName package com.google.oboe.sample.rhythmgame ask for installer name.
04-25 15:35:03.170 2045-2226/? D/SystemGaService: sendCrashInfoToRemote successful
04-25 15:35:03.171 2045-7195/? W/ActivityManager:   Force finishing activity com.google.oboe.sample.rhythmgame/.MainActivity
04-25 15:35:03.171 2045-7195/? E/ActivityManager: Will notifyMovedToHome from moveHomeStack
04-25 15:35:03.171 2045-7195/? E/ActivityManager: Broadcasting Moved to Home screen Intent
04-25 15:35:03.172 2045-7195/? D/VirtualKeyBackLightService: full screen state = false
04-25 15:35:03.341 327-429/? I/ThermalEngine: Sensor:pa_therm1:37000 mC
04-25 15:35:03.474 2045-7195/? I/WindowManager: Screenshot max retries 4 of Token{710d633 ActivityRecord{f97f9a2 u0 com.google.oboe.sample.rhythmgame/.MainActivity t2029 f}} appWin=Window{1031afa u0 Starting com.google.oboe.sample.rhythmgame} drawState=4
04-25 15:35:03.562 4187-4187/? I/ActivityThread: Performing receive of Intent { act=org.codeaurora.action.stk.idle_screen flg=0x10000010 cmp=com.android.stk/.StkCmdReceiver (has extras) }: app=android.app.Application@175519, appName=com.android.stk, pkg=com.android.stk, comp={com.android.stk/com.android.stk.StkCmdReceiver}, dir=/system/app/Stk/Stk.apk, duration=69
04-25 15:35:03.569 4829-4829/? D/TaskWatcherService: pkgName: com.asus.launcher taskId: 1798
04-25 15:35:03.569 4829-4829/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1242 android.content.ContextWrapper.startService:588 com.asus.powersaver.TaskWatcherService$IncomingHandler.handleMessage:-1 android.os.Handler.dispatchMessage:102 android.os.Looper.loop:153 
04-25 15:35:03.575 4829-4829/? D/PowerSaverService: onStartCommand PowerSaverService
04-25 15:35:03.577 4829-4829/? D/PowerSaverService: current package:com.asus.launcher;activity:com.android.launcher3.Launcher
04-25 15:35:03.577 4829-4829/? D/PowerSaverUtils: isLimitedCpuFrequency prop : 0 ; result : false
04-25 15:35:03.604 4829-5215/? D/OpenedTimeAppInfoProvider: Update DB : number of affected records : 1
04-25 15:35:03.612 2045-17755/? I/OpenGLRenderer: Initialized EGL, version 1.4
04-25 15:35:03.624 4829-5215/? I/AppOpsStatusUpdateHandler: pkgName = com.asus.launcher
04-25 15:35:03.624 4829-5215/? I/AppOpsStatusUpdateHandler: taskId = 1798
04-25 15:35:03.636 3618-3618/? D/PhoneStatusBar: setSystemUiVisibility vis=8000 mask=ffffffff oldVal=8600 newVal=8000 diff=600
04-25 15:35:03.982 2045-2227/? W/ActivityManager: Activity pause timeout for ActivityRecord{f97f9a2 u0 com.google.oboe.sample.rhythmgame/.MainActivity t2029 f}
04-25 15:35:03.989 2045-2227/? D/WindowManager: adjustConfigurationLw, config:{0 1.0 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h616dp 320dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
04-25 15:35:03.991 2045-2227/? D/ActivityManager: [MemInfo] Before resuming ActivityRecord{5e76a67 u0 com.asus.launcher/com.android.launcher3.Launcher t1798}. System free memory=604762112
04-25 15:35:04.055 4119-4119/? V/Launcher: [onResume] called
04-25 15:35:04.056 4119-4119/? I/Launcher: Time spent in onResume: 1ms
04-25 15:35:04.064 4119-4119/? D/Launcher.Utilities: isPhone= true
```

**Comment by dturner** [comment]
Thanks for this. Please could you try disabling Instant Run in Android Studio. 

Instructions: https://stackoverflow.com/a/44947396/824903

**Comment by interstar** [comment]
No. The logcat is quieter but similar message :

```
04-25 19:22:54.612 31229-31229/? I/art: Late-enabling -Xcheck:jni
04-25 19:22:54.712 31229-31229/com.google.oboe.sample.rhythmgame W/System: ClassLoader referenced unknown path: /data/app/com.google.oboe.sample.rhythmgame-2/lib/arm
04-25 19:22:54.715 31229-31229/com.google.oboe.sample.rhythmgame V/Monotype: SetAppTypeFace- try to flip, app = com.google.oboe.sample.rhythmgame
04-25 19:22:54.717 31229-31229/com.google.oboe.sample.rhythmgame V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
04-25 19:22:54.726 31229-31229/com.google.oboe.sample.rhythmgame D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
04-25 19:22:54.727 31229-31229/com.google.oboe.sample.rhythmgame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.oboe.sample.rhythmgame, PID: 31229
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.oboe.sample.rhythmgame-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.oboe.sample.rhythmgame-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.oboe.sample.rhythmgame.MainActivity.<clinit>(MainActivity.java:28)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2336)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5472)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 19:22:57.168 31229-31229/? I/Process: Sending signal. PID: 31229 SIG: 9

```

**Comment by philburk** [comment]
> couldn't find "libnative-lib.so

It is not loading the native library. So it is probably a build issue, not a bug in the native code itself.

That device uses a Qualcomm Snapdragon 400 (Cortex A7 - ARMv7) 

build.gradle has abiFilters:   'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'

**Comment by interstar** [comment]
@philburk What does that actually mean? 

I'm not an expert Android developer. So when you say "build" problem, do you mean it's a bug in the Gradle script? Or something that I should have installed in Android studio independently of this project? (În which case, what? I installed the NDK ... isn't that enough?)

Or something completely different? 

How do I go about trying to solve this?

**Comment by philburk** [comment]
Hello Phil,

by build problem I just meant that the problem seems to be in the early
phase of either compiling or linking the program. The library that contains
Oboe itself was not loaded. So Oboe did not have a chance to run. So it is
not a runtime bug in oboe.

I don't know yet where the problem is. It could be in the NDK or in the
gradle script or something else. I'm just trying to narrow down the realm
of possibility.

Phil Burk

**Comment by dturner** [comment]
@interstar Sorry for all the problems you've been having Phil. 

@philburk is right, it sounds like a problem with the build process, however, the sample should "just work" regardless of target device. 

Are you getting any errors during the build process - sometimes Android Studio can hide these. Make sure you click on Toggle View (the box with a > in it) to check the output of the multiple build systems (CMake and Gradle). 

![image](https://user-images.githubusercontent.com/873212/56975934-bbeb2a00-6b69-11e9-8015-2dfc104bce8b.png)

**Comment by interstar** [comment]
FYI ... I tried it again.

If you check the full app. out of the repository, it works. If you go back to the tutorial version ie. before you start adding the code in, it fails the first step that the tutorial says should compile.

Maybe there's something wrong in the build file in the tutorial branch.

**Comment by dturner** [comment]
I recently made a big update to this codelab which should have fixed this problem. Please try it again and let me know if you still have issues.

**Comment by interstar** [comment]
> I recently made a big update to this codelab which should have fixed this problem. Please try it again and let me know if you still have issues.

Coming back to this. I can't find the codelab for Oboe. Does it still exist? Is Oboe still the way I should develop audio apps for Android?

**Comment by dturner** [comment]
Yes, the codelab should still exist. We made some updates to our internal infrastructure recently and it might have got lost. I will investigate.
